name: AI Telegram Auto Poster

on:
  schedule:
    - cron: "30 4 * * *"
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  generate-and-post:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      # ==============================
      # CHECKOUT REPOSITORY
      # ==============================
      - name: Checkout repository
        uses: actions/checkout@v4


      # ==============================
      # SET UP PYTHON
      # ==============================
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      # ==============================
      # INSTALL LIBRARIES
      # ==============================
      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade huggingface_hub pillow google-genai


      # ==============================
      # RUN BOT
      # ==============================
      - name: Run bot
        env:
         
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          POLLINATIONS_API_KEY: ${{ secrets.POLLINATIONS_API_KEY }}

        run: |
          python bot.py
